### ISSUE TITLE
Spices?

### ISSUE THREAD

**Issue by kongtianshou** [IntroToCode/Spring21_Recipes_Codemates4#4]
## 💬 Discussion topic

Will it be ok if we include spices in our recipes? 

## ❗ Potential issues

Maybe some people will not like certain spices

## 👥 People to consult

All teammates

## 📃 Details
Please list the spicies you would want to avoid if there is any

**Comment by chwong11** [comment]
What recipe are we talking about?

**Comment by LSallersonberk** [comment]
This is for the marinara sauce I believe?

**Comment by johnaeastman** [comment]
SPICEY NO NICE-Y!!!! ‼️

**Comment by kongtianshou** [comment]
lol, awesome. No additional spices then.
