### ISSUE TITLE
Toppings for Chia Seed Pudding (breakfast) recipe

### ISSUE THREAD

**Issue by johnaeastman** [IntroToCode/Spring21_Recipes_Codemates4#5]
## 💬 Discussion topic

Good chia seed pudding must have TOPPINGS! I've included a delicious recipe in here for the pudding, but we need the team to determine what the best toppings to include are!

## ❗ Potential issues

Everyone has different preferences for toppings — it's okay to mix and match!

## 👥 People to consult

@kongtianshou
@tfantis
@chwong11
@LSallersonberk

## 📃 Details

Please [commit changes](https://github.com/IntroToCode/Spring21_Recipes_Codemates4/pull/1) to the Pull Request for review by teammates. Once we've all contributed, we'll have a fully-fledged recipe!

**Comment by kongtianshou** [comment]
Sounds good. Would love to have more diversity of toppings!

**Comment by caroline-tsoi** [comment]
Hi, I don't think I'm part of this group, please remove me :) Thanks!

**Comment by LSallersonberk** [comment]
I am fine with the current topping mix.

**Comment by johnaeastman** [comment]
> Hi, I don't think I'm part of this group, please remove me :) Thanks!

🤦‍♂️ Removed — sorry!

**Comment by chwong11** [comment]
This is definitively the best combination of toppings?

**Comment by johnaeastman** [comment]
Looks like everyone likes the toppings, and we're good to go here! Closing the comment.
