### ISSUE TITLE
Quick easy Lunch to avoid the afternoon zzz

### ISSUE THREAD

**Issue by chwong11** [IntroToCode/Spring21_Recipes_Codemates4#6]
## 💬 Discussion topic
Guacamole is yummy, light, and low in sugar that causes you to crash, especially as you get older...what do you guys think?

## ❗ Potential issues
Not sure what kind of chips you guys like, but I always go for tortilla chips

## 👥 People to consult
@kongtianshou 
@tfantis
@johnaeastman 
@LSallersonberk

## 📃 Details
Added suggested ingredients as a place for you guys to make commits to...

**Comment by kongtianshou** [comment]
Love the idea!  Sweet potato chips are my favorite. Can go with tortilla chips

**Comment by LSallersonberk** [comment]
I think a mix of differently colored tortilla chips would be the best option in terms of aesthetics.

**Comment by chwong11** [comment]
great, donezo
